language: node_js
node_js: node
deploy:
  provider: heroku
  edge: true
  api_key:
    secure: 3b4202ff-02f6-4f59-9d60-ba914d7afe32
  app: whispering-escarpment-34402
  on:
    repo: Kaleidics/team-finder-app
